name: Deploy to OpenShift

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/
          sudo mv kubectl /usr/local/bin/
          oc version

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Build Docker image
        run: |
            docker build -t photos-app-test:latest .


      - name: Deploy to OpenShift
        run: |
          oc project balazsvrg-dev
          oc set image deployment/photos-app-test-git photos-app-test-git=photos-app-test:latest
          oc rollout restart deployment/photos-app-test-git
