name: Deploy to OpenShift

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          server: ${{ secrets.OPENSHIFT_SERVER }}
          token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.OPENSHIFT_SERVER }}/photos-app-test:latest .
          docker push ${{ secrets.OPENSHIFT_SERVER }}/photos-app-test:latest

      - name: Deploy to OpenShift
        run: |
          oc project balazsvrg-dev
          oc set image deployment/ photos-app-test-git  photos-app-test-git=${{ secrets.OPENSHIFT_SERVER }}/photos-app-test:latest
          oc rollout latest deployment/photos-app-test-git
